# # Database Configuration
# spring.datasource.url=jdbc:postgresql://dpg-d51b5pchg0os73bppdi0-a.singapore-postgres.render.com:5432/uat_boxcorner_art?currentSchema=uat
# spring.datasource.username=uat_boxcorner_art_user
# spring.datasource.password=HM7nrO5KNV4Wz5icB0WJ8vfgWj0GOztJ
# spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA Configuration
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # Server Configuration
# server.port=8080


# Database Configuration
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres?currentSchema=public
spring.datasource.username=postgres
spring.datasource.password=Panu11111*
spring.datasource.driver-class-name=org.postgresql.Driver

# JPA Configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# Server Configuration
server.port=8080

# # Database Configuration
# spring.datasource.url=jdbc:postgresql://db:5432/mydb?currentSchema=public
# spring.datasource.username=admin
# spring.datasource.password=password123
# spring.datasource.driver-class-name=org.postgresql.Driver

# # JPA Configuration
# spring.jpa.hibernate.ddl-auto=update
# spring.jpa.show-sql=true
# spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

# # Server Configuration
# server.port=8080